<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2009-07-31 16:16

$extensionClassesPath = t3lib_extMgm::extPath('mvc_extjs_samples') . 'Classes/';
return array(
	'tx_mvcextjssamples_controller_blankmodulecontroller' => $extensionClassesPath . 'Controller/BlankModuleController.php',
	'tx_mvcextjssamples_controller_feuseradmincontroller' => $extensionClassesPath . 'Controller/FeUserAdminController.php',
	'tx_mvcextjssamples_controller_feedscontroller' => $extensionClassesPath . 'Controller/FeedsController.php',
	'tx_mvcextjssamples_controller_genrecontroller' => $extensionClassesPath . 'Controller/GenreController.php',
	'tx_mvcextjssamples_controller_helloworldcontroller' => $extensionClassesPath . 'Controller/HelloWorldController.php',
	'tx_mvcextjssamples_controller_moviecontroller' => $extensionClassesPath . 'Controller/MovieController.php',
	'tx_mvcextjssamples_controller_oldstylemodulecontroller' => $extensionClassesPath . 'Controller/OldStyleModuleController.php',
	'tx_mvcextjssamples_controller_pictureslideshowcontroller' => $extensionClassesPath . 'Controller/PictureSlideShowController.php',
	'tx_mvcextjssamples_controller_simpleformcontroller' => $extensionClassesPath . 'Controller/SimpleFormController.php',
	'tx_mvcextjssamples_controller_simplemodulefunctioncontroller' => $extensionClassesPath . 'Controller/SimpleModuleFunctionController.php',
	'tx_mvcextjssamples_controller_twittercontroller' => $extensionClassesPath . 'Controller/TwitterController.php',
	'tx_mvcextjssamples_domain_model_genre' => $extensionClassesPath . 'Domain/Model/Genre.php',
	'tx_mvcextjssamples_domain_model_genrerepository' => $extensionClassesPath . 'Domain/Model/GenreRepository.php',
	'tx_mvcextjssamples_domain_model_movie' => $extensionClassesPath . 'Domain/Model/Movie.php',
	'tx_mvcextjssamples_domain_model_movierepository' => $extensionClassesPath . 'Domain/Model/MovieRepository.php',
);
?>